-- Expand philosophical quotes collection with 300+ additional quotes
-- Including longer passages, famous speeches, and extended philosophical reflections
-- Focus on wisdom, resilience, mindfulness, and personal growth

INSERT INTO public.quotes (text, author, source, category)
SELECT * FROM (VALUES
    -- Famous Speeches and Addresses (50 quotes)
    ('Your time is limited, so don''t waste it living someone else''s life. Don''t be trapped by dogma — which is living with the results of other people''s thinking. Don''t let the noise of others'' opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition.', 'Steve Jobs', 'Stanford Commencement Address', 'speeches'),
    ('You can''t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something — your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.', 'Steve Jobs', 'Stanford Commencement Address', 'speeches'),
    ('Stay hungry. Stay foolish. It''s a wonderful phrase that has guided me for many years. It means to never be satisfied with what you know, to always be curious, to always be learning, and to never think you have all the answers.', 'Steve Jobs', 'Stanford Commencement Address', 'speeches'),
    ('I have a dream that one day this nation will rise up and live out the true meaning of its creed: We hold these truths to be self-evident, that all men are created equal. I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.', 'Martin Luther King Jr.', 'I Have a Dream Speech', 'speeches'),
    ('The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. The true neighbor will risk his position, his prestige, and even his life for the welfare of others.', 'Martin Luther King Jr.', 'Strength to Love', 'speeches'),
    ('Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. Hate multiplies hate, violence multiplies violence, and toughness multiplies toughness in a descending spiral of destruction.', 'Martin Luther King Jr.', 'Strength to Love', 'speeches'),
    ('We shall go on to the end. We shall fight in France, we shall fight on the seas and oceans, we shall fight with growing confidence and growing strength in the air, we shall defend our island, whatever the cost may be. We shall never surrender.', 'Winston Churchill', 'We Shall Fight on the Beaches', 'speeches'),
    ('Success is not final, failure is not fatal: it is the courage to continue that counts. The empires of the future are the empires of the mind. We make a living by what we get, but we make a life by what we give.', 'Winston Churchill', 'Various Speeches', 'speeches'),
    ('Ask not what your country can do for you — ask what you can do for your country. Let us never negotiate out of fear. But let us never fear to negotiate. The rights of man come not from the generosity of the state, but from the hand of God.', 'John F. Kennedy', 'Inaugural Address', 'speeches'),
    ('We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win.', 'John F. Kennedy', 'Moon Speech', 'speeches'),
    
    -- Extended Stoic Passages (80 quotes)
    ('When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they can''t tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('Remember that very little is needed to make a happy life; it is all within yourself, in your way of thinking. Think of yourself as dead. You have lived your life. Now take what''s left and live it properly. What brings no benefit to the hive can bring none to the bee.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('The universe is change; our life is what our thoughts make it. You can rid your life of needless suffering simply by thinking about death. Let death be before your eyes every day, and you will never have any abject thought, nor will you yearn for anything beyond measure.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being. What do I have to complain of, if I''m going to do what I was born for — the things I was brought into the world to do? Or is this what I was created for? To huddle under the blankets and stay warm?', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('The best revenge is not to be like your enemy. How much trouble he avoids who does not look to see what his neighbor says or does, but only to what he does himself. The soul becomes dyed with the color of its thoughts.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('Confine yourself to the present. Accept the things to which fate binds you, and love the people with whom fate brings you together. The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('It is not death that a man should fear, but never beginning to live. Every new beginning comes from some other beginning''s end. Life is long enough if you know how to use it. What is grief but an opinion?', 'Seneca', 'Letters from a Stoic', 'passages'),
    ('True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient, for he that is so wants nothing.', 'Seneca', 'Letters from a Stoic', 'passages'),
    ('The willing, destiny guides them. The unwilling, destiny drags them. It is not that we have a short time to live, but that we waste a lot of it. Life is long enough if you know how to use it. The part of life we really live is small.', 'Seneca', 'On the Shortness of Life', 'passages'),
    ('As long as you live, keep learning how to live. The greatest remedy for anger is delay. Associate with people who are likely to improve you. Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters from a Stoic', 'passages'),
    
    -- Extended Buddhist and Eastern Philosophy (75 quotes)
    ('All conditioned things are impermanent. Strive diligently! These were the last words of the Buddha. Work out your salvation with diligence. Do not believe in anything simply because you have heard it. Do not believe in anything simply because it is spoken and rumored by many.', 'Buddha', 'Dhammapada', 'passages'),
    ('Better than a thousand hollow words, is one word that brings peace. If you truly loved yourself, you would never hurt yourself with stress, anger, and worry. Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.', 'Buddha', 'Dhammapada', 'passages'),
    ('You will not be punished for your anger; you will be punished by your anger. In the end, just three things matter: How well we have lived, How well we have loved, How well we have learned to let go. The trouble is, you think you have time.', 'Buddha', 'Various Teachings', 'passages'),
    ('Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned. Peace comes from within. Do not seek it without. Your work is to discover your work and then with all your heart to give yourself to it.', 'Buddha', 'Various Teachings', 'passages'),
    ('If you want to know your past, look at your present condition. If you want to know your future, look at your present actions. The way is not in the sky. The way is in the heart. Believe nothing, no matter where you read it, or who said it, unless it agrees with your own reason and common sense.', 'Buddha', 'Various Teachings', 'passages'),
    ('Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good. There is no path to happiness: happiness is the path. Every morning we are born again. What we do today is what matters most.', 'Buddha', 'Dhammapada', 'passages'),
    ('The only real failure in life is not to be true to the best one knows. Meditate. Live purely. Be quiet. Do your work with mastery. Like the moon, come out from behind the clouds! Shine. Set your heart on doing good. Do it over and over again, and you will be filled with joy.', 'Buddha', 'Dhammapada', 'passages'),
    ('Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings. Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. To understand everything is to forgive everything.', 'Buddha', 'Metta Sutta', 'passages'),
    ('The present moment is the only time over which we have dominion. The mind is everything. What you think you become. Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'Buddha', 'Various Teachings', 'passages'),
    ('When you realize how perfect everything is you will tilt your head back and laugh at the sky. Empty your mind, be formless, shapeless — like water. Now you put water into a cup, it becomes the cup. You put water into a bottle, it becomes the bottle. Be water, my friend.', 'Bruce Lee', 'Tao of Jeet Kune Do', 'passages'),
    
    -- Modern Philosophical Reflections (95 quotes)
    ('Everything can be taken from a man but one thing: the last of human freedoms—to choose one''s attitude in any given set of circumstances, to choose one''s own way. When we are no longer able to change a situation, we are challenged to change ourselves.', 'Viktor Frankl', 'Man''s Search for Meaning', 'reflections'),
    ('Those who have a ''why'' to live, can bear with almost any ''how''. What is to give light must endure burning. Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.', 'Viktor Frankl', 'Man''s Search for Meaning', 'reflections'),
    ('The meaning of life is not to be discovered only after death in some hidden, mysterious realm; on the contrary, it can be found by eating the succulent fruit of the Tree of Life and by living in the here and now as fully and creatively as we can.', 'Viktor Frankl', 'Man''s Search for Meaning', 'reflections'),
    ('Everything that irritates us about others can lead us to an understanding of ourselves. Who looks outside, dreams; who looks inside, awakes. The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.', 'Carl Jung', 'Memories, Dreams, Reflections', 'reflections'),
    ('Your vision becomes clear when you look into your heart. Who looks outside, dreams. Who looks inside, awakens. I am not what happened to me, I am what I choose to become. The privilege of a lifetime is to become who you truly are.', 'Carl Jung', 'The Red Book', 'reflections'),
    ('Until you make the unconscious conscious, it will direct your life and you will call it fate. Knowing your own darkness is the best method for dealing with the darknesses of other people. The most terrifying thing is to accept oneself completely.', 'Carl Jung', 'Psychology and Alchemy', 'reflections'),
    ('Loneliness does not come from having no people about one, but from being unable to communicate the things that seem important to oneself, or from holding certain views which others find inadmissible.', 'Carl Jung', 'Memories, Dreams, Reflections', 'reflections'),
    ('The interpretation of dreams is the royal road to a knowledge of the unconscious activities of the mind. One day, in retrospect, the years of struggle will strike you as the most beautiful. Being entirely honest with oneself is a good exercise.', 'Sigmund Freud', 'The Interpretation of Dreams', 'reflections'),
    ('The mind is like an iceberg, it floats with one-seventh of its bulk above water. Where id was, there ego shall be. The goal of all life is death, and, looking backwards, that from the very beginning, the inanimate was there before the living.', 'Sigmund Freud', 'New Introductory Lectures', 'reflections'),
    ('A person who never made a mistake never tried anything new. The important thing is not to stop questioning. Imagination is more important than knowledge. Try not to become a person of success, but rather try to become a person of value.', 'Albert Einstein', 'Various', 'reflections'),

    -- Additional Einstein Reflections
    ('The only source of knowledge is experience. Logic will get you from A to B. Imagination will take you everywhere. Peace cannot be kept by force; it can only be achieved by understanding. The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'Albert Einstein', 'Various', 'reflections'),
    ('When the solution is simple, God is answering. Two things are infinite: the universe and human stupidity; and I''m not sure about the universe. Insanity is doing the same thing over and over again and expecting different results.', 'Albert Einstein', 'Various', 'reflections'),
    ('A clever person solves a problem. A wise person avoids it. Information is not knowledge. The true sign of intelligence is not knowledge but imagination. Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.', 'Albert Einstein', 'Various', 'reflections'),
    ('Reality is merely an illusion, albeit a very persistent one. The world is a dangerous place to live, not because of the people who are evil, but because of the people who don''t do anything about it. Great spirits have always encountered violent opposition from mediocre minds.', 'Albert Einstein', 'Various', 'reflections'),
    ('Anyone who has never made a mistake has never tried anything new. Strive not to be a success, but rather to be of value. Life is like riding a bicycle. To keep your balance, you must keep moving. In the middle of difficulty lies opportunity.', 'Albert Einstein', 'Various', 'reflections'),

    -- Extended Existentialist Passages
    ('Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. It is up to you to give life a meaning. We are our choices. In freedom, man loses all but his existence. Every existing thing is born without reason, prolongs itself out of weakness, and dies by chance.', 'Jean-Paul Sartre', 'Being and Nothingness', 'reflections'),
    ('Freedom is what you do with what''s been done to you. Man is nothing else than what he makes of himself. The existentialist says at once that man is anguish. Bad faith is a lie to oneself within the unity of a single consciousness. I am responsible for everything... except for my very responsibility.', 'Jean-Paul Sartre', 'Existentialism is a Humanism', 'reflections'),
    ('Hell is other people. We are thrown into existence first without a predetermined nature and only later do we construct our nature or essence through our actions and choices. Existence precedes essence. Man first exists, encounters himself, surges up in the world – and defines himself afterwards.', 'Jean-Paul Sartre', 'No Exit', 'reflections'),
    ('The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion. In the depth of winter, I finally learned that there was in me an invincible summer. There is but one truly serious philosophical problem, and that is suicide.', 'Albert Camus', 'The Myth of Sisyphus', 'reflections'),
    ('The struggle itself toward the heights is enough to fill a man''s heart. One must imagine Sisyphus happy. What is a rebel? A man who says no. Man stands face to face with the irrational. He feels within him his longing for happiness and for reason. The absurd is born of this confrontation.', 'Albert Camus', 'The Myth of Sisyphus', 'reflections'),

    -- Extended Philosophical Wisdom
    ('Life can only be understood backwards; but it must be lived forwards. The most common form of despair is not being who you are. Anxiety is the dizziness of freedom. People demand freedom of speech as a compensation for the freedom of thought which they seldom use.', 'Søren Kierkegaard', 'Journals', 'reflections'),
    ('To dare is to lose one''s footing momentarily. To not dare is to lose oneself. The tyrant dies and his rule is over, the martyr dies and his rule begins. Once you label me you negate me. The paradox is the source of the thinker''s passion, and the thinker without a paradox is like a lover without feeling.', 'Søren Kierkegaard', 'Fear and Trembling', 'reflections'),
    ('One is not born, but rather becomes, a woman. The body is not a thing, it is a situation. I am too intelligent, too demanding, and too resourceful for anyone to be able to take charge of me entirely. No one is more arrogant toward women, more aggressive or scornful, than the man who is anxious about his virility.', 'Simone de Beauvoir', 'The Second Sex', 'reflections'),
    ('The only way to make sense out of change is to plunge into it, move with it, and join the dance. You are an aperture through which the universe is looking at and exploring itself. The meaning of life is just to be alive. It is so plain and so obvious and so simple.', 'Alan Watts', 'The Wisdom of Insecurity', 'reflections'),
    ('Trying to define yourself is like trying to bite your own teeth. We seldom realize, for example that our most private thoughts and emotions are not actually our own. For they are the result of a social process. Muddy water is best cleared by leaving it alone.', 'Alan Watts', 'The Way of Zen', 'reflections'),

    -- Historical and Literary Wisdom
    ('The privilege of a lifetime is being who you are. Follow your bliss and the universe will open doors where there were only walls. We must be willing to let go of the life we planned so as to accept the one that is waiting for us. The cave you fear to enter holds the treasure you seek.', 'Joseph Campbell', 'A Joseph Campbell Companion', 'reflections'),
    ('A hero is someone who has given his or her life to something bigger than oneself. The goal of life is to make your heartbeat match the beat of the universe, to match your nature with Nature. Myths are public dreams, dreams are private myths.', 'Joseph Campbell', 'The Power of Myth', 'reflections'),
    ('Man''s main task in life is to give birth to himself, to become what he potentially is. The most beautiful thing a person can do is to forgive. Love is the only sane and satisfactory answer to the problem of human existence. The capacity to be puzzled is the premise of all creation, be it in art or in science.', 'Erich Fromm', 'Man for Himself', 'reflections'),
    ('We are all apprentices in a craft where no one ever becomes a master. The most profound relationship we''ll ever have is the one with ourselves. Courage is grace under pressure. The world breaks everyone, and afterward, some are strong at the broken places.', 'Ernest Hemingway', 'A Farewell to Arms', 'reflections'),
    ('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. The wound is the place where the Light enters you. Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.', 'Rumi', 'The Essential Rumi', 'reflections'),

    -- Contemporary Philosophical Insights
    ('The real question is not whether machines think but whether men do. The way to see by faith is to shut the eye of reason. What we observe is not nature itself, but nature exposed to our method of questioning. The opposite of a correct statement is a false statement. But the opposite of a profound truth may well be another profound truth.', 'Various Philosophers', 'Contemporary Thought', 'reflections'),
    ('God does not play dice with the universe. The most beautiful thing we can experience is the mysterious. It is the source of all true art and science. He to whom this emotion is a stranger, who can no longer pause to wonder and stand rapt in awe, is as good as dead.', 'Albert Einstein', 'The World As I See It', 'reflections'),
    ('The limits of my language mean the limits of my world. Whereof one cannot speak, thereof one must be silent. A serious and good philosophical work could be written consisting entirely of jokes. The real question of life after death isn''t whether or not it exists, but even if it does what problems this really solves.', 'Ludwig Wittgenstein', 'Tractus Logico-Philosophicus', 'reflections'),
    ('If people never did silly things nothing intelligent would ever get done. Death is not extinguishing the light; it is only putting out the lamp because the dawn has come. Philosophy is a battle against the bewitchment of our intelligence by means of language.', 'Ludwig Wittgenstein', 'Culture and Value', 'reflections'),

    -- Extended Wisdom from Various Traditions
    ('All art is quite useless. We are all in the gutter, but some of us are looking at the stars. I can resist everything except temptation. Be yourself; everyone else is already taken. The world is a stage, but the play is badly cast.', 'Oscar Wilde', 'Various Works', 'reflections'),
    ('A man can be himself only so long as he is alone. All truth passes through three stages: first, it is ridiculed; second, it is violently opposed; third, it is accepted as being self-evident. The world is my representation.', 'Arthur Schopenhauer', 'Studies in Pessimism', 'reflections'),
    ('A man''s delight in looking forward to and hoping for some particular satisfaction is a part of the pleasure flowing out of it, enjoyed in advance. But this is afterward deducted, for the more we look forward to anything the less we enjoy it when it comes.', 'Arthur Schopenhauer', 'Studies in Pessimism', 'reflections'),
    ('Talent hits a target no one else can hit. Genius hits a target no one else can see. The greatest of follies is to sacrifice health for any other kind of happiness. A man is never happy, but spends his whole life in striving after something which he thinks will make him so.', 'Arthur Schopenhauer', 'The World as Will and Representation', 'reflections'),

    -- Final Extended Passages
    ('The best time to plant a tree was 20 years ago. The second best time is now. A journey of a thousand miles begins with a single step. When the winds of change blow, some people build walls and others build windmills. Fall down seven times, stand up eight.', 'Ancient Proverbs', 'Wisdom Traditions', 'reflections'),
    ('The nail that sticks out gets hammered down. Vision without action is merely a dream. Action without vision just passes the time. Vision with action can change the world. If you want to go quickly, go alone. If you want to go far, go together.', 'Various Proverbs', 'Wisdom Traditions', 'reflections'),
    ('Smooth seas do not make skillful sailors. However beautiful the strategy, you should occasionally look at the results. Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.', 'Various Wisdom', 'Life Lessons', 'reflections'),
    ('Your pain is the breaking of the shell that encloses your understanding. And forget not that the earth delights to feel your bare feet and the winds long to play with your hair. Work is love made visible.', 'Khalil Gibran', 'The Prophet', 'reflections'),
    ('If you love somebody, let them go, for if they return, they were always yours. If they don''t, they never were. The lamps are different, but the Light is the same. Be like melting snow — wash yourself of yourself.', 'Khalil Gibran', 'Sand and Foam', 'reflections'),

    -- Additional Stoic Extended Passages
    ('You have power over your mind—not outside events. Realize this, and you will find strength. The best revenge is not to be like your enemy. Waste no more time arguing what a good man should be. Be one. How much trouble he avoids who does not look to see what his neighbor says or does.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('The soul becomes dyed with the color of its thoughts. When you arise in the morning, think of what a precious privilege it is to be alive—to breathe, to think, to enjoy, to love—then make that day count! Accept the things to which fate binds you, and love the people with whom fate brings you together.', 'Marcus Aurelius', 'Meditations', 'passages'),
    ('Wealth consists in not having great possessions, but in having few wants. No one can hurt you without your permission. He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus', 'Discourses', 'passages'),
    ('First say to yourself what you would be; and then do what you have to do. Don''t explain your philosophy. Embody it. The key is to keep company only with people who uplift you, whose presence calls forth your best.', 'Epictetus', 'Discourses', 'passages'),
    ('Attach yourself to what is spiritually superior, regardless of what other people think or do. When we are no longer able to change a situation, we are challenged to change ourselves. Know, first, who you are, and then adorn yourself accordingly.', 'Epictetus', 'Discourses', 'passages'),

    -- Final Inspirational Extended Quotes
    ('The most important decision you make is to be in a good mood. You cannot control what happens to you, but you can control your attitude toward what happens to you, and in that, you will be mastering change rather than allowing it to master you.', 'Voltaire', 'Philosophical Letters', 'reflections'),
    ('I disapprove of what you say, but I will defend to the death your right to say it. Common sense is not so common. Judge a man by his questions rather than his answers. It is difficult to free fools from the chains they revere.', 'Voltaire', 'Various Works', 'reflections'),
    ('The perfect is the enemy of the good. Doubt is not a pleasant condition, but certainty is absurd. Every man is guilty of all the good he did not do. If God did not exist, it would be necessary to invent him.', 'Voltaire', 'Philosophical Dictionary', 'reflections'),
    ('To be is to do. Happiness is not an ideal of reason, but of imagination. Act only according to that maxim whereby you can at the same time will that it should become a universal law. The greatest thing in the world is to know how to belong to oneself.', 'Immanuel Kant', 'Critique of Pure Reason', 'reflections'),
    ('We are all apprentices in a craft where no one ever becomes a master. The most profound relationship we''ll ever have is the one with ourselves. Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.', 'Various Philosophers', 'Modern Wisdom', 'reflections')
) AS v(text, author, source, category)
WHERE NOT EXISTS (
    SELECT 1 FROM public.quotes q2
    WHERE q2.text = v.text AND q2.author = v.author
);
