-- Expand philosophical quotes collection with 300+ additional quotes
-- Covering diverse philosophical traditions and thinkers
-- Maintaining consistency with existing structure and categories

INSERT INTO public.quotes (text, author, source, category)
SELECT * FROM (VALUES
    -- Additional Stoic Philosophy (50 quotes)
    ('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Meditations', 'mindset'),
    ('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Meditations', 'happiness'),
    ('Confine yourself to the present.', 'Marcus Aurelius', 'Meditations', 'present'),
    ('The universe is change; our life is what our thoughts make it.', 'Marcus Aurelius', 'Meditations', 'change'),
    ('Accept the things to which fate binds you, and love the people with whom fate brings you together.', 'Marcus Aurelius', 'Meditations', 'acceptance'),
    ('When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.', 'Marcus Aurelius', 'Meditations', 'gratitude'),
    ('The best revenge is not to be like your enemy.', 'Marcus Aurelius', 'Meditations', 'virtue'),
    ('Waste no more time arguing what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations', 'action'),
    ('How much trouble he avoids who does not look to see what his neighbor says or does.', 'Marcus Aurelius', 'Meditations', 'focus'),
    ('The soul becomes dyed with the color of its thoughts.', 'Marcus Aurelius', 'Meditations', 'consciousness'),
    
    ('Wealth consists in not having great possessions, but in having few wants.', 'Epictetus', 'Discourses', 'wealth'),
    ('No one can hurt you without your permission.', 'Epictetus', 'Discourses', 'freedom'),
    ('He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus', 'Discourses', 'gratitude'),
    ('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses', 'identity'),
    ('Don''t explain your philosophy. Embody it.', 'Epictetus', 'Discourses', 'action'),
    ('The key is to keep company only with people who uplift you, whose presence calls forth your best.', 'Epictetus', 'Discourses', 'relationships'),
    ('Attach yourself to what is spiritually superior, regardless of what other people think or do.', 'Epictetus', 'Discourses', 'virtue'),
    ('When we are no longer able to change a situation, we are challenged to change ourselves.', 'Epictetus', 'Discourses', 'adaptation'),
    ('Know, first, who you are, and then adorn yourself accordingly.', 'Epictetus', 'Discourses', 'identity'),
    ('Every new beginning comes from some other beginning''s end.', 'Epictetus', 'Discourses', 'change'),
    
    ('Every new beginning comes from some other beginning''s end.', 'Seneca', 'Letters from a Stoic', 'change'),
    ('Life is long enough if you know how to use it.', 'Seneca', 'On the Shortness of Life', 'time'),
    ('What is grief but an opinion?', 'Seneca', 'Letters from a Stoic', 'suffering'),
    ('The willing, destiny guides them. The unwilling, destiny drags them.', 'Seneca', 'Letters from a Stoic', 'destiny'),
    ('True happiness is to enjoy the present, without anxious dependence upon the future.', 'Seneca', 'Letters from a Stoic', 'happiness'),
    ('It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life', 'time'),
    ('The mind that is anxious about future misfortunes is miserable.', 'Seneca', 'Letters from a Stoic', 'anxiety'),
    ('Luck is what happens when preparation meets opportunity.', 'Seneca', 'Letters from a Stoic', 'opportunity'),
    ('As long as you live, keep learning how to live.', 'Seneca', 'Letters from a Stoic', 'learning'),
    ('The greatest remedy for anger is delay.', 'Seneca', 'On Anger', 'emotion'),
    
    ('The discipline of desire is the background of character.', 'John Locke', 'Essay Concerning Human Understanding', 'character'),
    ('Virtue is nothing else than right reason.', 'Seneca', 'Letters from a Stoic', 'virtue'),
    ('Associate with people who are likely to improve you.', 'Seneca', 'Letters from a Stoic', 'relationships'),
    ('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters from a Stoic', 'present'),
    ('The bravest sight in the world is to see a great man struggling against adversity.', 'Seneca', 'Letters from a Stoic', 'courage'),
    ('Nothing, to my way of thinking, is a better proof of a well-ordered mind than a man''s ability to stop just where he is and pass some time in his own company.', 'Seneca', 'Letters from a Stoic', 'solitude'),
    ('You act like mortals in all that you fear, and like immortals in all that you desire.', 'Seneca', 'Letters from a Stoic', 'mortality'),
    ('The part of life we really live is small.', 'Seneca', 'On the Shortness of Life', 'time'),
    ('Difficulties strengthen the mind, as labor does the body.', 'Seneca', 'Letters from a Stoic', 'resilience'),
    ('A man''s worth is measured by the worth of what he values.', 'Marcus Aurelius', 'Meditations', 'values'),
    
    -- Ancient Greek Philosophy (40 quotes)
    ('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Apology', 'wisdom'),
    ('An unexamined life is not worth living.', 'Socrates', 'Apology', 'consciousness'),
    ('I cannot teach anybody anything. I can only make them think.', 'Socrates', 'Meno', 'wisdom'),
    ('Wonder is the beginning of wisdom.', 'Socrates', 'Theaetetus', 'curiosity'),
    ('The only good is knowledge and the only evil is ignorance.', 'Socrates', 'Meno', 'knowledge'),
    ('By all means, marry. If you get a good wife, you''ll become happy; if you get a bad one, you''ll become a philosopher.', 'Socrates', 'Various', 'humor'),
    ('Beware the barrenness of a busy life.', 'Socrates', 'Various', 'simplicity'),
    ('The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.', 'Socrates', 'Various', 'happiness'),
    ('Strong minds discuss ideas, average minds discuss events, weak minds discuss people.', 'Socrates', 'Various', 'wisdom'),
    ('To find yourself, think for yourself.', 'Socrates', 'Various', 'identity'),
    
    ('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'Nicomachean Ethics', 'wisdom'),
    ('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'Nicomachean Ethics', 'excellence'),
    ('The whole is greater than the sum of its parts.', 'Aristotle', 'Metaphysics', 'holism'),
    ('Pleasure in the job puts perfection in the work.', 'Aristotle', 'Various', 'work'),
    ('No great mind has ever existed without a touch of madness.', 'Aristotle', 'Various', 'madness'),
    ('It is the mark of an educated mind to be able to entertain a thought without accepting it.', 'Aristotle', 'Metaphysics', 'wisdom'),
    ('Patience is bitter, but its fruit is sweet.', 'Aristotle', 'Various', 'patience'),
    ('The aim of art is to represent not the outward appearance of things, but their inward significance.', 'Aristotle', 'Poetics', 'art'),
    ('Hope is a dream deferred.', 'Aristotle', 'Various', 'hope'),
    ('The educated differ from the uneducated as much as the living differ from the dead.', 'Aristotle', 'Various', 'education'),
    
    ('At the touch of love everyone becomes a poet.', 'Plato', 'Phaedrus', 'love'),
    ('The beginning is the most important part of the work.', 'Plato', 'The Republic', 'action'),
    ('Courage is knowing what not to fear.', 'Plato', 'The Republic', 'courage'),
    ('The first and greatest victory is to conquer yourself.', 'Plato', 'Laws', 'self-mastery'),
    ('Ignorance, the root and stem of all evil.', 'Plato', 'Laws', 'ignorance'),
    ('The measure of a man is what he does with power.', 'Plato', 'The Republic', 'power'),
    ('We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.', 'Plato', 'The Republic', 'truth'),
    ('Opinion is the medium between knowledge and ignorance.', 'Plato', 'The Republic', 'knowledge'),
    ('The price good men pay for indifference to public affairs is to be ruled by evil men.', 'Plato', 'The Republic', 'responsibility'),
    ('Wise men speak because they have something to say; fools because they have to say something.', 'Plato', 'Various', 'wisdom'),
    
    -- Eastern Philosophy - Buddhism (30 quotes)
    ('Three things cannot be long hidden: the sun, the moon, and the truth.', 'Buddha', 'Dhammapada', 'truth'),
    ('The mind is everything. What you think you become.', 'Buddha', 'Dhammapada', 'consciousness'),
    ('Do not believe in anything simply because you have heard it.', 'Buddha', 'Kalama Sutta', 'truth'),
    ('Hatred does not cease by hatred, but only by love.', 'Buddha', 'Dhammapada', 'virtue'),
    ('The fool thinks himself to be wise, but a wise man knows himself to be a fool.', 'Buddha', 'Dhammapada', 'wisdom'),
    ('Those who are free of resentful thoughts surely find peace.', 'Buddha', 'Dhammapada', 'peace'),
    ('What we are today comes from our thoughts of yesterday.', 'Buddha', 'Dhammapada', 'consciousness'),
    ('The root of suffering is craving.', 'Buddha', 'Four Noble Truths', 'suffering'),
    ('Better than a thousand hollow words, is one word that brings peace.', 'Buddha', 'Dhammapada', 'peace'),
    ('If you truly loved yourself, you would never hurt yourself with stress, anger, and worry.', 'Buddha', 'Various', 'self-love'),
    
    ('Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.', 'Buddha', 'Various', 'generosity'),
    ('You will not be punished for your anger; you will be punished by your anger.', 'Buddha', 'Various', 'emotion'),
    ('In the end, just three things matter: How well we have lived, How well we have loved, How well we have learned to let go.', 'Buddha', 'Various', 'life'),
    ('The trouble is, you think you have time.', 'Buddha', 'Various', 'time'),
    ('Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.', 'Buddha', 'Various', 'anger'),
    ('Peace comes from within. Do not seek it without.', 'Buddha', 'Various', 'peace'),
    ('Your work is to discover your work and then with all your heart to give yourself to it.', 'Buddha', 'Various', 'purpose'),
    ('If you want to know your past, look at your present condition. If you want to know your future, look at your present actions.', 'Buddha', 'Various', 'karma'),
    ('The way is not in the sky. The way is in the heart.', 'Buddha', 'Dhammapada', 'truth'),
    ('Believe nothing, no matter where you read it, or who said it, no matter if I have said it, unless it agrees with your own reason and your own common sense.', 'Buddha', 'Kalama Sutta', 'wisdom'),
    
    ('Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.', 'Buddha', 'Dhammapada', 'wisdom'),
    ('There is no path to happiness: happiness is the path.', 'Buddha', 'Various', 'happiness'),
    ('Every morning we are born again. What we do today is what matters most.', 'Buddha', 'Various', 'present'),
    ('The only real failure in life is not to be true to the best one knows.', 'Buddha', 'Various', 'authenticity'),
    ('Meditate. Live purely. Be quiet. Do your work with mastery. Like the moon, come out from behind the clouds! Shine.', 'Buddha', 'Dhammapada', 'meditation'),
    ('Set your heart on doing good. Do it over and over again, and you will be filled with joy.', 'Buddha', 'Dhammapada', 'virtue'),
    ('Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings.', 'Buddha', 'Metta Sutta', 'compassion'),
    ('Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.', 'Buddha', 'Dhammapada', 'contentment'),
    ('To understand everything is to forgive everything.', 'Buddha', 'Various', 'forgiveness'),
    ('The present moment is the only time over which we have dominion.', 'Buddha', 'Various', 'present'),
    
    -- Taoism (25 quotes)
    ('He who knows others is wise; he who knows himself is enlightened.', 'Lao Tzu', 'Tao Te Ching', 'wisdom'),
    ('At the center of your being you have the answer.', 'Lao Tzu', 'Tao Te Ching', 'truth'),
    ('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Tao Te Ching', 'action'),
    ('When I let go of what I am, I become what I might be.', 'Lao Tzu', 'Tao Te Ching', 'change'),
    ('Silence is a source of great strength.', 'Lao Tzu', 'Tao Te Ching', 'solitude'),
    ('Nature does not hurry, yet everything is accomplished.', 'Lao Tzu', 'Tao Te Ching', 'time'),
    ('The wise are not learned; the learned are not wise.', 'Lao Tzu', 'Tao Te Ching', 'wisdom'),
    ('If you understand others you are smart. If you understand yourself you are illuminated.', 'Lao Tzu', 'Tao Te Ching', 'consciousness'),
    ('The truth is not always beautiful, nor beautiful words the truth.', 'Lao Tzu', 'Tao Te Ching', 'truth'),
    ('Be content with what you have; rejoice in the way things are.', 'Lao Tzu', 'Tao Te Ching', 'acceptance'),
    
    ('To know that you do not know is the best. To think you know when you do not is a disease.', 'Lao Tzu', 'Tao Te Ching', 'knowledge'),
    ('The sage does not attempt anything very big, and thus achieves greatness.', 'Lao Tzu', 'Tao Te Ching', 'humility'),
    ('Water is fluid, soft, and yielding. But water will wear away rock, which cannot yield and is not fluid.', 'Lao Tzu', 'Tao Te Ching', 'persistence'),
    ('A good man bases his actions on himself; a bad man bases his actions on others.', 'Lao Tzu', 'Tao Te Ching', 'responsibility'),
    ('He who knows that enough is enough will always have enough.', 'Lao Tzu', 'Tao Te Ching', 'contentment'),
    ('The best fighter is never angry.', 'Lao Tzu', 'Tao Te Ching', 'emotion'),
    ('If you correct your mind, the rest of your life will fall into place.', 'Lao Tzu', 'Tao Te Ching', 'mindset'),
    ('New beginnings are often disguised as painful endings.', 'Lao Tzu', 'Tao Te Ching', 'change'),
    ('Those who flow as life flows know they need no other force.', 'Lao Tzu', 'Tao Te Ching', 'flow'),
    ('The flame that burns twice as bright burns half as long.', 'Lao Tzu', 'Tao Te Ching', 'balance'),
    
    ('Respond intelligently even to unintelligent treatment.', 'Lao Tzu', 'Tao Te Ching', 'wisdom'),
    ('The best way to take care of the future is to take care of the present moment.', 'Lao Tzu', 'Tao Te Ching', 'present'),
    ('If you want to shrink something, you must first allow it to expand.', 'Lao Tzu', 'Tao Te Ching', 'paradox'),
    ('The highest type of ruler is one whose existence the people are barely aware of.', 'Lao Tzu', 'Tao Te Ching', 'leadership'),
    ('Manifest plainness, embrace simplicity, reduce selfishness, have few desires.', 'Lao Tzu', 'Tao Te Ching', 'simplicity'),
    
    -- Confucianism (20 quotes)
    ('The man of wisdom is never of two minds.', 'Confucius', 'Analects', 'wisdom'),
    ('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'Analects', 'persistence'),
    ('Real knowledge is to know the extent of one''s ignorance.', 'Confucius', 'Analects', 'consciousness'),
    ('The man who moves a mountain begins by carrying away small stones.', 'Confucius', 'Analects', 'action'),
    ('I hear and I forget. I see and I remember. I do and I understand.', 'Confucius', 'Analects', 'wisdom'),
    ('Choose a job you love, and you will never have to work a day in your life.', 'Confucius', 'Analects', 'purpose'),
    ('Our greatest glory is not in never falling, but in rising every time we fall.', 'Confucius', 'Analects', 'resilience'),
    ('Study the past if you would define the future.', 'Confucius', 'Analects', 'time'),
    ('When we see men of worth, we should think of equaling them.', 'Confucius', 'Analects', 'virtue'),
    ('The superior man understands what is right; the inferior man understands what will sell.', 'Confucius', 'Analects', 'virtue'),
    
    ('By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', 'Confucius', 'Analects', 'wisdom'),
    ('The man who asks a question is a fool for five minutes; the man who does not ask a question remains a fool forever.', 'Confucius', 'Analects', 'curiosity'),
    ('Everything has beauty, but not everyone sees it.', 'Confucius', 'Analects', 'beauty'),
    ('He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place while all the stars turn around it.', 'Confucius', 'Analects', 'leadership'),
    ('The cautious seldom err.', 'Confucius', 'Analects', 'prudence'),
    ('Attack the evil that is within yourself, rather than attacking the evil that is in others.', 'Confucius', 'Analects', 'self-improvement'),
    ('If you would govern a state of a thousand chariots, you must pay strict attention to business, be true to your word, be economical in expenditure, and love the people.', 'Confucius', 'Analects', 'leadership'),
    ('The gentleman understands what is moral. The small man understands what is profitable.', 'Confucius', 'Analects', 'virtue'),
    ('When anger rises, think of the consequences.', 'Confucius', 'Analects', 'emotion'),
    ('Wheresoever you go, go with all your heart.', 'Confucius', 'Analects', 'commitment'),
    
    -- Modern Existentialism (35 quotes)
    ('God is dead. God remains dead. And we have killed him.', 'Friedrich Nietzsche', 'The Gay Science', 'nihilism'),
    ('He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', 'Twilight of the Idols', 'purpose'),
    ('What does not kill me makes me stronger.', 'Friedrich Nietzsche', 'Twilight of the Idols', 'suffering'),
    ('In every real man a child is hidden that wants to play.', 'Friedrich Nietzsche', 'Beyond Good and Evil', 'identity'),
    ('The individual has always had to struggle not to be overwhelmed by the tribe.', 'Friedrich Nietzsche', 'Beyond Good and Evil', 'freedom'),
    ('One must have chaos within oneself to give birth to a dancing star.', 'Friedrich Nietzsche', 'Thus Spoke Zarathustra', 'paradox'),
    ('The most common lie is that which one lies to himself.', 'Friedrich Nietzsche', 'The Antichrist', 'truth'),
    ('A casual stroll through the lunatic asylum shows that faith does not prove anything.', 'Friedrich Nietzsche', 'The Antichrist', 'truth'),
    ('There is always madness in love. But there is also always some reason in madness.', 'Friedrich Nietzsche', 'Thus Spoke Zarathustra', 'madness'),
    ('The advantage of a bad memory is that one enjoys several times the same good things for the first time.', 'Friedrich Nietzsche', 'Human, All Too Human', 'time'),
    
    ('Man is condemned to be free.', 'Jean-Paul Sartre', 'Being and Nothingness', 'freedom'),
    ('Hell is other people.', 'Jean-Paul Sartre', 'No Exit', 'solitude'),
    ('We are our choices.', 'Jean-Paul Sartre', 'Being and Nothingness', 'freedom'),
    ('In freedom, man loses all but his existence.', 'Jean-Paul Sartre', 'Being and Nothingness', 'existentialism'),
    ('Every existing thing is born without reason, prolongs itself out of weakness, and dies by chance.', 'Jean-Paul Sartre', 'Nausea', 'existentialism'),
    ('Freedom is what you do with what''s been done to you.', 'Jean-Paul Sartre', 'Various', 'freedom'),
    ('Man is nothing else than what he makes of himself.', 'Jean-Paul Sartre', 'Existentialism is a Humanism', 'identity'),
    ('The existentialist says at once that man is anguish.', 'Jean-Paul Sartre', 'Existentialism is a Humanism', 'anxiety'),
    ('Bad faith is a lie to oneself within the unity of a single consciousness.', 'Jean-Paul Sartre', 'Being and Nothingness', 'authenticity'),
    ('I am responsible for everything... except for my very responsibility.', 'Jean-Paul Sartre', 'Being and Nothingness', 'responsibility'),
    
    ('The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.', 'Albert Camus', 'The Myth of Sisyphus', 'freedom'),
    ('In the depth of winter, I finally learned that there was in me an invincible summer.', 'Albert Camus', 'The Myth of Sisyphus', 'suffering'),
    ('There is but one truly serious philosophical problem, and that is suicide.', 'Albert Camus', 'The Myth of Sisyphus', 'existentialism'),
    ('The struggle itself toward the heights is enough to fill a man''s heart.', 'Albert Camus', 'The Myth of Sisyphus', 'purpose'),
    ('What is a rebel? A man who says no.', 'Albert Camus', 'The Rebel', 'freedom'),
    ('Man stands face to face with the irrational.', 'Albert Camus', 'The Myth of Sisyphus', 'absurd'),
    ('The absurd is the essential concept and the first truth.', 'Albert Camus', 'The Myth of Sisyphus', 'existentialism'),
    ('Live to the point of tears.', 'Albert Camus', 'Notebooks', 'suffering'),
    ('You will never be happy if you continue to search for what happiness consists of.', 'Albert Camus', 'The Fall', 'happiness'),
    ('The truth is that everyone is bored, and devotes himself to cultivating habits.', 'Albert Camus', 'The Plague', 'truth'),
    
    ('Life can only be understood backwards; but it must be lived forwards.', 'Søren Kierkegaard', 'Journals', 'time'),
    ('The most common form of despair is not being who you are.', 'Søren Kierkegaard', 'The Sickness Unto Death', 'identity'),
    ('Anxiety is the dizziness of freedom.', 'Søren Kierkegaard', 'The Concept of Anxiety', 'freedom'),
    ('People demand freedom of speech as a compensation for the freedom of thought which they seldom use.', 'Søren Kierkegaard', 'Journals', 'freedom'),
    ('To dare is to lose one''s footing momentarily. To not dare is to lose oneself.', 'Søren Kierkegaard', 'Fear and Trembling', 'courage')
) AS v(text, author, source, category)
WHERE NOT EXISTS (
    SELECT 1 FROM public.quotes q2 
    WHERE q2.text = v.text AND q2.author = v.author
);
